app:
  name: velox-raptor
  env: development

telegram:
  bot_token: 8557882253:AAHTccrtBq9GQ_sO6lRytXNcCbtOjUvIA7o
  polling_timeout: 60

database:
  driver: postgres
  host: localhost
  port: 5432
  user: velox_user
  password: veloxpass
  name: velox_raptor_saham
  sslmode: disable
  max_open_conn: 20
  max_idle_conn: 10

python_service:
  url: "https://sanjuanita-fasciate-karry.ngrok-free.dev"
  timeout_second: 120

limit:
  bot_message_per_second: 25
  per_chat_delay_ms: 1100
